# This file has been generated by node2nix 1.9.0. Do not edit!

{ napalm }:
  napalm.buildPackage ./0.8.2
    { packageLock = ./0.8.2/package-lock.json;
      preNpmHook = ''
        mkdir -p $out/bin
        ln -s $out/_napalm-install/node_modules/.bin/psa $out/bin/psa
      '';
    }
